# Deep Research Clone 設定ファイル例（改善版）
# このファイルを config.yaml にコピーして使用してください

# 言語モデル設定
language_model:
  # デフォルトモデル: ollama, openai, gemini
  default: "ollama"

  # Ollama設定
  ollama:
    model_name: "llama3.1:8b"
    base_url: "http://localhost:11434"  # 別のポートを使用する場合は変更

  # OpenAI設定
  openai:
    model: "gpt-3.5-turbo"
    max_tokens: 2000
    temperature: 0.7

  # Google Gemini設定
  gemini:
    model: "gemini-2.0-flash"
    temperature: 0.7

# 反復改善設定
iteration:
  # 最大反復回数
  max_iterations: 6

  # 初期検索結果数
  initial_search_count: 8

  # 追加検索結果数
  additional_search_count: 5

  # 追加検索クエリの最大数
  max_additional_queries: 3

# Web検索設定
search:
  # デフォルト検索エンジン: google, bing, duckduckgo
  engine: "google"

  # 検索結果数
  max_results: 5

  # レート制限設定
  rate_limit:
    requests_per_second: 2  # 1秒あたりのリクエスト数（より保守的に）
    max_retries: 5          # 最大リトライ回数（増加）
    retry_delay_base: 5     # 基本待機時間（秒）（増加）

  # Google Custom Search設定
  google:
    api_key: "${GOOGLE_SEARCH_API_KEY}"
    search_engine_id: "${GOOGLE_SEARCH_ENGINE_ID}"

# 引用管理設定
citations:
  # 引用の自動抽出を有効にする
  auto_extract: true

  # 関連度スコアの閾値
  relevance_threshold: 0.5

  # 信頼性スコアの閾値（この値未満の結果は除外）
  reliability_threshold: 0.3

  # 引用形式: numbered, author_year, url
  format: "numbered"

# 出力設定
output:
  # デフォルト出力形式: markdown, pdf, html
  format: "markdown"

  # 出力ディレクトリ
  directory: "./output"

  # ファイル名テンプレート
  filename_template: "research_{query}_{timestamp}"

  # ファイル名生成設定
  filename_generation:
    # 重複時の処理方法: timestamp, version, both
    duplicate_handling: "both"
    # タイムスタンプ形式: YYYYMMDD_HHMMSS, YYYY-MM-DD_HH-MM-SS
    timestamp_format: "YYYYMMDD_HHMMSS"
    # バージョン番号のプレフィックス
    version_prefix: "v"

  # マークダウン設定
  markdown:
    include_search_results: true
    include_analysis: true
    include_summary: true
    include_final_report: true
    include_citations: true
    include_search_history: true

# ログ設定
logging:
  level: "INFO"
  file: "deep_research.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# プロンプト設定
prompts:
  analysis: |
    今日の日付情報: {today_info}

    以下の検索結果のみを基に、'{query}'について構造化された分析を行ってください。検索結果に含まれていない情報は推測せず、事実のみを記載してください。

    検索結果:
    {results_text}

    ## 分析の指示

    以下のカテゴリに分けて、検索結果を分析してください：

    ### 1. 主要な事実（重要度順）
    - 検索結果から得られる最も重要な事実を5-10個抽出
    - 各事実に具体的なデータや数値を添える
    - 時系列での変化があれば明記

    ### 2. 市場・業界データ
    - 市場規模、シェア、成長率などの数値情報
    - 統計データや調査結果
    - 競合状況や業界動向

    ### 3. 時系列分析
    - 過去から現在までの変化
    - 将来の予定や計画
    - トレンドやパターンの分析

    ### 4. 課題と機会
    - 現在の課題や問題点
    - 将来の機会や可能性
    - リスク要因

    ### 5. 不明な点・追加調査項目
    - 検索結果からは不明な点
    - 追加で調べるべき項目
    - 情報の限界や制約

    ## 重要な注意事項

    1. **事実ベース**: 検索結果に含まれている情報のみを使用
    2. **具体的なデータ**: 数値、統計、事例を積極的に活用
    3. **時系列の理解**: 過去・現在・将来を明確に区別
    4. **信頼性の評価**: 情報源の信頼性について言及
    5. **客観性**: 推測や主観を避け、事実のみを記載

    上記の指示に従って、構造化された分析を行ってください。

  analysis_all: |
    今日の日付情報: {today_info}

    以下の全ての検索結果のみを基に、'{query}'について包括的な調査結果を作成してください。検索結果に含まれていない情報は推測せず、事実のみを記載してください。

    検索結果:
    {results_text}

    分析では以下の点を含めてください：
    - 検索結果から得られる主要な事実（重要度順）
    - 検索結果に含まれる具体的なデータや統計
    - 検索結果から読み取れる異なる視点や意見の比較
    - 各情報の日付（検索結果に含まれる場合）と今日との関係
    - 将来の予定や過去の情報の区別
    - 信頼性の高い情報源からの情報
    - 検索結果からは不明な点や課題

    重要：検索結果に含まれていない情報は記載せず、事実のみを記載してください。
    分析結果を日本語で詳しく記述してください。

  summary: |
    以下の分析結果のみを基に、'{query}'について簡潔で実用的な要約を作成してください。分析結果に含まれていない情報は推測せず、事実のみを記載してください。

    分析結果:
    {analysis}

    ## 要約作成の指示

    以下の要素を含む、200-300文字の要約を作成してください：

    ### 1. 重要な事実（3-5点）
    - 最も重要な発見事項を箇条書きで
    - 具体的な数値やデータを含める

    ### 2. 主要な結論
    - 分析結果から導かれる結論
    - 実用的な示唆や提言

    ### 3. 重要な日付情報
    - 時系列での重要な変化
    - 将来の予定や計画

    ## 重要な注意事項

    1. **簡潔性**: 200-300文字に収める
    2. **実用性**: 読者が実用的な情報を得られる内容
    3. **具体性**: 抽象的な表現を避け、具体的なデータを含める
    4. **客観性**: 事実に基づいた客観的な記述
    5. **構造化**: 見出しや箇条書きを効果的に使用

    上記の指示に従って、簡潔で実用的な要約を作成してください。

  additional_queries: |
    今日の日付情報: {today_info}

    以下の研究結果をレビューして、追加で調べるべきキーワードや検索クエリを提案してください。

    元のクエリ: {original_query}

    分析結果:
    {analysis}

    要約:
    {summary}

    以下の観点から追加検索キーワードを提案してください：
    1. 分析で言及されているが詳細が不足している概念
    2. 関連する専門用語や技術
    3. 比較対象となる他の事例やデータ
    4. 最新の情報や統計
    5. 反対意見や異なる視点
    6. 古い情報（過去の予定や発売日）について最新状況を確認するべき項目
    7. 将来の予定について最新の進捗状況を確認するべき項目

    特に、記事内で発売予定日や発表予定日が今日より前の場合は、実際の発売・発表状況を確認するための検索キーワードを提案してください。
    また、将来の予定について最新の進捗や変更がないか確認するためのキーワードも提案してください。

    各キーワードは具体的で検索しやすい形で提案してください。
    以下の形式で最大5つのキーワードを提案してください：

    キーワード1
    キーワード2
    キーワード3
    キーワード4
    キーワード5

    番号や記号は付けずに、キーワードのみを改行区切りで記載してください。

  final_report: |
    今日の日付情報: {today_info}

    以下の分析結果と要約を基に、'{query}'について専門的で読みやすい研究レポートを作成してください。

    分析結果:
    {analysis}

    要約:
    {summary}

    ## レポート作成の指示

    以下の構造で、学術的で専門的なレポートを作成してください：

    ### 1. エグゼクティブサマリー（200-300文字）
    - 最も重要な発見事項を3-5点にまとめる
    - 具体的な数値やデータを含める
    - 結論を簡潔に述べる

    ### 2. 研究背景と目的
    - 研究テーマの重要性と背景
    - 本研究の目的と意義
    - 研究の範囲と制限

    ### 3. 主要な発見事項
    - 検索結果から得られた重要な事実をカテゴリ別に整理
    - 各発見事項に具体的なデータや例を添える
    - 情報源の信頼性について言及

    ### 4. 市場分析・業界動向
    - 市場規模、トレンド、競合状況
    - 時系列での変化や予測
    - 業界全体の課題と機会

    ### 5. 課題と機会
    - 現在の課題や問題点
    - 将来の機会や可能性
    - 改善提案や推奨事項

    ### 6. 結論と提言
    - 主要な結論をまとめる
    - 具体的なアクションプラン
    - 今後の研究方向

    ## 重要な注意事項

    1. **重複を避ける**: エグゼクティブサマリーと本文で同じ内容を繰り返さない
    2. **情報の優先順位**: 最も重要な情報から順に記載
    3. **具体的なデータ**: 数値、統計、事例を積極的に活用
    4. **客観性**: 事実に基づいた客観的な記述
    5. **読みやすさ**: 専門的でありながら理解しやすい文章
    6. **構造化**: 見出し、箇条書き、表などを効果的に使用

    ## 文体とトーン

    - 専門的で信頼性の高い文体
    - ビジネス文書として適切な形式
    - 読者が実用的な情報を得られる内容
    - 学術的でありながら実践的

    上記の指示に従って、高品質な研究レポートを作成してください。
